apiVersion: v1
kind: Service
metadata:
  name: minha-app-service
spec:
  type: NodePort
  selector:
    app: minha-app
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
    nodePort: 30081

